### ISSUE TITLE
Not working on 1.19.2

### ISSUE THREAD

**Issue by Twincher** [Gecolay/GSit#75]
![image](https://user-images.githubusercontent.com/49343819/196040083-5ea13797-561d-4488-b9ef-4b932df548c7.png)

**Comment by Gecolay** [comment]
Can you provide more info? Server version, plugins, ...

**Comment by Twincher** [comment]
> Can you provide more info? server type, plugins, ...

![image](https://user-images.githubusercontent.com/49343819/196236457-4bf90401-b3a0-40c1-80a6-8c73b2b9b6e2.png)
Mirai 1.19.2

**Comment by Gecolay** [comment]
You don't use a supported version. Check out the spigot page: "Supports Spigot, Paper (+ all Forks) Servers from 1.13.x to 1.19.x!"
It clearly says Paper + all Forks not that a fork of a fork of a fork of a fork is supported.

**Comment by Gecolay** [comment]
There is no line saying anything about: "supported paper + all paper based server types". So please keep this in mind.

**Comment by Gecolay** [comment]
@Twincher can you confirm that it works on paper or a paper fork for you, so we can close this issue? When a server does not support the GSit features GSit will not work on it, this isn't a GSit issue here.
Also please remove your spigot review, because it does not relate to a real problem.

Thank you! If you have any further questions just ask here or on the discord server!

**Comment by Twincher** [comment]
Working on 1.19.2 PaperSpigot, thx
